name: aurora_assessment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.1
  get_it: ^9.2.0
  mobx: ^2.6.0
  flutter_mobx: ^2.0.7
  palette_generator_master: ^1.0.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  mobx_codegen: ^2.7.6

flutter:
  uses-material-design: true
